services:
  authentication-service:
    extra_hosts:
      - "keycloak.local:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication-service
    ports:
      - "8082:8082"
    env_file:
      - .env.docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME: keycloak.local
      KC_HOSTNAME_PORT: 8081
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:

networks:
  default:
    name: innowise-network
    external: true