services.user-service.url=${USER_SERVICE_URL}
keycloak.server-url=${KEYCLOAK_URL}

keycloak.realm=user-service

keycloak.client-id=user-service
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}