services.user-service.url=${USER_SERVICE_URL}
keycloak.server-url=${KEYCLOAK_URL}

keycloak.realm=user-service

keycloak.client-id=user-service
keycloak.admin.username=${KEYCLOAK_ADMIN}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}